// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TvcDay11JQueryAjax.Models;

#nullable disable

namespace TvcDay11JQueryAjax.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20251029094606_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TvcDay11JQueryAjax.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TvcStudent", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 19,
                            Name = "Nguyễn Văn An"
                        },
                        new
                        {
                            Id = 2,
                            Age = 20,
                            Name = "Trần Thị Bình"
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            Name = "Lê Văn Cường"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
